### ISSUE TITLE
Aspect Assignment Crash

### ISSUE THREAD

**Issue by TheCrimsonSpark** [Azanor/thaumcraft#1847] opened 2015-08-12 14:38 UTC
http://pastebin.com/zHgUXWA5
While playing around on our server, We discovered that when we added project E, opening the Aspect page in the thaumonomicon, crashes with this log here. It seems that your assignment cycle is looping causing the crash.

**Comment by sctjkc01** [comment] 2015-08-12 15:15
Warning: duplicate of my issue - Azanor/thaumcraft#1805

**Closed** 2015-10-12 07:06 UTC
