### ISSUE TITLE
Sometimes CV beams do not render transparently.

### ISSUE THREAD

**Issue by Boingboingsplat** [Azanor/thaumcraft#1426] opened 2014-12-26 21:58 UTC
This has been occurring to me for a while, but I haven't gotten around to reporting it now.

Occasionally the CV beams do not render as semitransparent. Exiting and reloading the world fixes the issue, but usually they will lose their transparency again later once I have left the area and return. In this example I had them rendering fine, but the newly placed Vis Relay created a beam that rendered without transparency:

![2014-12-26_16 33 20](https://cloud.githubusercontent.com/assets/7320818/5559553/a96fb6d4-8d1f-11e4-894f-c62303023fed.png)

I'm using an XFX Radeon HD 6870 video card.
Running Thaumcraft 4.2.2.1 and Forge 10.13.2.1277.

Let me know if you need any more information.

**Comment by beepbeat** [comment] 2015-01-03 17:16
I got it with this Setup, when I break-replaye active relays
![2015-01-03_18 06 13](https://cloud.githubusercontent.com/assets/7950771/5603120/856281a8-9374-11e4-84c8-049321941337.png)

As soon as I deactivate the arcane bore, it fixes itself.

**Comment by chrisbecke** [comment] 2015-01-12 12:10
Are you running that AE2 system off of cv/t? Is that a thing?

**Comment by forsaken1111** [comment] 2015-01-12 12:11
He has a creative energy cell there

**Comment by forsaken1111** [comment] 2015-01-12 12:12
He has a creative energy cell there.

**Comment by chrisbecke** [comment] 2015-01-12 12:13
Ah - its just there to power the (hidden) mining laser.
Still. It should be a thing.

**Comment by Amelia-** [comment] 2015-02-04 13:23
I have seen this as well and it seems to be caused by logistics pipes power suppliers (in the world I play on anyway). When you have those built and running it makes beams of energy go trough the pipes but it tends to cause this visual issue with the relays.
If I set the following setting to false in the logistics pipes config file they do not render the power beams anymore but the relay network will look normal:
"B:enableParticleFX=true"

**Comment by Azanor** [comment] 2015-02-05 07:52
In regards to both this and any other vis-relay related issues:
They are going away in the 1.8 version of Thaumcraft and for the most part I have stopped working on the 1.7.10 version. So, I'm going to close this.

**Closed by Azanor** 2015-02-05 07:52 UTC
Labels: investigate
