### ISSUE TITLE
UUIDs not being Used

### ISSUE THREAD

**Issue by SgtHotshot** [Azanor/thaumcraft#1581] opened 2015-02-04 17:32 UTC
I changed my Minecraft Username from SgtHotshot09 to SgtHotshot and when I logged back on I discovered that all my Thaumcraft progress had been reset.  It looks like two files are still based on the username rather than the uuid  <Username>.baub and <Username>.thaum

**Comment by forsaken1111** [comment] 2015-02-04 17:52
It's known, and it may change in the future but it's not a bug. You'll have to manually re-add your old research progress using the console commands.

**Comment by SgtHotshot** [comment] 2015-02-04 19:00
How is not using UUIDs not a bug when Forge and Minecraft itself are using UUIDs?  UUIDs have been in effect for a while now so using usernames as the file name for that user's settings just doesn't make sense.

**Comment by forsaken1111** [comment] 2015-02-04 19:16
A bug is an error, flaw, failure, or fault in a computer program. The mod was written to use the username for ID, not the UUID, because it was developed before minecraft adopted the UUID. As I said, it may change in the future. I'm obviously not Azanor so don't take this as gospel but I have seen this exact question answered already.

**Comment by MalkContent** [comment] 2015-02-04 19:52
uuids actually were being used at one point but this caused problems, see here: https://github.com/Azanor/thaumcraft/issues/1056

**Comment by SgtHotshot** [comment] 2015-02-04 19:56
Hmm it says it was suppose to be fixed in the next version of TC.  Has a new version of TC came out since then?

**Comment by MalkContent** [comment] 2015-02-04 19:57
cmon. read a changelog, will ya...

**Comment by ThePB** [comment] 2015-02-04 20:14
Just to barge in... you could try to see if renaming the .baub and .thaum files in your save to your new username does give you your research back? I'm kind of interested but have no intention to change my username :D I suppose yours is just the first time this behavior will be reported in the near future.

Azanor, should if work?

**Comment by SgtHotshot** [comment] 2015-02-04 20:16
yeah it does work.  I just know it's going to be a bigger issue now since people can change their usernames.

**Comment by SgtHotshot** [comment] 2015-02-04 20:18
I just don't think people who just play for fun with really no knowledge on commands or minecraft files should be forced to mess around with either files or commands to get their research back.  I know Azanor has tried to implement it but couldn't get it to reliably work.

**Comment by forsaken1111** [comment] 2015-02-04 20:19
I didn't mean to come across as if I were diminishing the issue, just informing you that I've seen it reported a few times and that Azanor has said it will probably change in future. Maybe something to look for in the 1.8 update.

**Comment by brandaop** [comment] 2015-02-05 01:31
Renaming files (USERNAME.thaum, USERNAME.thaumback, USERNAME.baub, USERNAME.baubback) seems to solve it partially. You can pick golems up and place them down again and they'll register you as their new owner as well. But I can't find a way around warded blocks (and doors, pressure plates, ETC.)

**Comment by Azanor** [comment] 2015-02-05 07:42
To be honest I will probably not change it to use UUID's. There is a disconnect between UUID's in offline, online and LAN made which was causing no end of problems which is why I switched back to using usernames instead. As far as I know this issue is still  not solved. People don't change their usernames much at all so the lesser of the two evils is making those that do have to rename their files. The alternative is much worse: people losing all their research everytime they play in offline mode or join a lan game.

As such I'm closing this issue. I am keeping an eye on the forge side of things if/when a solution appears.

**Closed by Azanor** 2015-02-05 07:42 UTC

**Comment by brandaop** [comment] 2015-02-05 12:09
Azanor, where in the files is the data about warded blocks and doors stored? I need to point the way to my admin so he can edit that on the server I play, as of now I am basically locked out of my impregnable base because of a name change. 

Love,
Pedro

**Comment by Azanor** [comment] 2015-02-05 12:21
Well, he will need to edit the nbt data for every single warded block. It will probably just be easier for him to unward them while opped and in creative mode.
