### ISSUE TITLE
Mana beans coming into existence on the other side of a log

### ISSUE THREAD

**Issue by seebs** [Azanor/thaumcraft#1476] opened 2015-01-05 09:31 UTC
So I have a room with a greatwood log ceiling, and mana beans growing under it, and a harvest golem. Mostly this works as expected, but occasionally a mana bean that results from this will appear above the ceiling rather than below it. Perhaps more terrifyingly, this was true when the space above it was solid stone; I would have to dig into it for a while to find beans to get the gather golem to stop staring forlornly at the ceiling. Perhaps the harvest golem should drop items where it stands, or something?

It may matter: The golems are standing on ethereal glass (from extra utilities) so they can reach the beans and I can walk through the room.

**Comment by chrisbecke** [comment] 2015-01-07 07:53
Dupe of [1729]

**Closed** 2015-01-09 07:28 UTC
