### ISSUE TITLE
Bug, Item Grate and AE2 in world craft

### ISSUE THREAD

**Issue by p75369** [Azanor/thaumcraft#1718] opened 2015-04-02 22:38 UTC
The item grate seems to do something that interupts in world crafting for AE2 (Fluix and the pure crystals).

Items dropped out of the grate do not craft when in the water.

**Comment by MalkContent** [comment] 2015-04-05 20:03
can you worldcraft with droppers/dispensers?

**Comment by p75369** [comment] 2015-04-06 08:40
Didn't try dispensers/droppers, but the Botania open crate works.

**Comment by MalkContent** [comment] 2015-04-06 08:52
If you have the grate directly above the water block, try putting it one block further above.

**Comment by p75369** [comment] 2015-04-06 09:40
Tried that. It was my first thought as I remembered the open crate needing an air block.

Sent from my phone.

---- MalkContent wrote ----

If you have the grate directly above the water block, try putting it one block further above.

---

**Comment by MalkContent** [comment] 2015-04-07 10:01
*shrugs*. make a water transport behind the grate and transport it into still water, see if it crafts there.

**Comment by p75369** [comment] 2015-04-07 12:47
Nope, still not growing. They will craft though, if you pick them up and drop them back in manually, so whatever it is, it's not permanently altering the seeds.

**Comment by Azanor** [comment] 2015-04-16 08:05
The grate will created items without a player name linked to them - normal MC dropped items remember who dropped them. I'm guessing AE requires this for some reason, though I can't think why.
I might change that for the next version, but since this isn't really a bug I will close this.

**Closed by Azanor** 2015-04-16 08:05 UTC

**Comment by Azanor** [comment] 2015-04-16 08:09
Actually, now that I looked at it, the problem is that the items dropped from the grate is actually a custom dropped entity. AE might be hardcoding to check for EntityItem, instead of checking for classes that extend it as well. Still something they need to fix on their side thougj :p
