### ISSUE TITLE
Crash-report

### ISSUE THREAD

**Issue by MrHelp** [Azanor/thaumcraft#1604] opened 2015-02-11 08:36 UTC
http://pastebin.com/jM1L0Qq8

**Comment by ThePB** [comment] 2015-02-11 13:05
Duplicate of this? https://github.com/Azanor/thaumcraft/issues/1550

**Comment by MrHelp** [comment] 2015-02-11 13:19
I think no. We have 4.2.3.4 verison ThaumCraft and this crash has when people create too much warned block in one chunk. I delete this blocks and they can login again.I don't know how it work but..

**Comment by Azanor** [comment] 2015-02-12 06:46
It is the same error. Closing this and referencing it in the other report.

**Closed by Azanor** 2015-02-12 06:46 UTC
