### ISSUE TITLE
coal and some block do not have aspects of magic

### ISSUE THREAD

**Issue by tech-boy101** [Azanor/thaumcraft#1765] opened 2015-05-04 05:14 UTC
i look a round whit new updata for thaumcraft use a new world and some mods and coal charcoal oak wood and sand and stone bricks and some more that i cant remind on the top of my head do not have aspects at all and sorry i not say some stuff like i can do grammar too good

**Comment by duhadventure** [comment] 2015-05-05 21:03
Screenshot? (F2 or Fn+F2)

**Comment by tech-boy101** [comment] 2015-05-07 04:05
![2015-05-06_23 02 42](https://cloud.githubusercontent.com/assets/10690514/7508336/648add50-f444-11e4-8f48-6af6a3ef5d83.png)

**Comment by duhadventure** [comment] 2015-05-07 18:03
Does the coal have metadata (EX: 131:3) (Meta is colon) or is it from different mod?

**Comment by tech-boy101** [comment] 2015-05-10 21:33
the coal id is 263/0 that mend

**Comment by tech-boy101** [comment] 2015-05-11 05:00
i dont no how get metadata

**Comment by Niacide** [comment] 2015-05-15 22:14
tech-boy101 is correct, coal and some blocks do not have aspects. This bug is caused by Extra Utilities.

To answer duhadventure's question, the value of the coal is 263:0 and this also effects charcoal (263:1). 

If you have mods present that allow the creation or coal/charcoal from clouds they will have aspects, but they will be wrong.

I have noticed  aspects coal, charcoal, and redstone blocks to be lacking aspects.I suspect there are more missing aspects.

For anyone that needs a fast solution to this problem you can use Coal Coke (Railcraft) or Sugar Charcoal (MineFactory Reloaded)

All testing was done with Extrautilities-1.2.4c and Thaumcraft-1.7.10-4.2.3.4/Thaumcraft-1.7.10-4.2.3.5

Hopefully this bug will be fixed.

**Comment by tech-boy101** [comment] 2015-05-16 03:27
so remove extrautilities for time be in

**Closed** 2015-05-25 06:11 UTC
