### ISSUE TITLE
Server Crashed thaumcraft 4.2.3.1

### ISSUE THREAD

**Issue by aldra2012** [Azanor/thaumcraft#1509] opened 2015-01-12 15:22 UTC
http://pastebin.com/yEBTQwTz

**Comment by Terpo** [comment] 2015-01-12 15:27
Same crash. Seems that another mod has to update its api. Without other mods its running fine.

**Comment by aldra2012** [comment] 2015-01-12 15:29
well then forget thaumcraft ill just delete it all.

**Comment by aldra2012** [comment] 2015-01-12 15:30
well than looks like i wont be updating for a long time then.

**Comment by xJon** [comment] 2015-01-12 16:25
Got the same crash on client.

**Comment by XanderDips** [comment] 2015-01-12 18:06
I am having the same problem. Seems like the conflict is IC2 and Thaumcraft...

**Comment by XanderDips** [comment] 2015-01-12 18:08
All my other mods work fine with it. Sadly IC2 and Thaumcraft are my 2 favorite mods.

**Comment by XanderDips** [comment] 2015-01-12 18:25
It also seems like TConstruct

**Comment by Barhandar** [comment] 2015-01-12 20:00
Anything which uses TC4 API will crash. Which means Flaxbeard's Steam Power, TConstruct, IC2, Railcraft, Magic Bees, any TC4 addons...

**Comment by Azanor** [comment] 2015-01-13 05:52
Yeah, this is a problem on my end, though I blame Thermal expansion and big reactors :P 
I had to move some code around because those two mods in combination was breaking all aspect assignments. Unfortunately moving the code broke many other mods. I will have to undo the change.

**Comment by Meegooo** [comment] 2015-01-13 06:38
Works fine with 4.2.3.2

**Comment by Reassembly** [comment] 2015-01-13 11:45
As noted in #1510 (restating here for clarity) this *specific* crash seems to be less caused by an API change and more caused by a problem with copper(/silver) wand cap research failing to fetch the appropriate recipes, triggered by any other mod adding copper(/silver) ingots to the game. This *was* apparently independent of Thaumcraft API calls, and could be triggered solely by adding the metal ingots to the ore dictionary.

However, I am also finding this to have been resolved with 4.2.3.2 - at least, neither Flaxbeard's Steam Power nor SimpleOres are causing Thaumcraft to crash on init for me. I suspect that IC2 (which also added copper ore) would have caused the same issue, and will probably work just fine with with TC 4.2.3.2.

...issue resolved & closed, maybe?

**Closed** 2015-01-13 12:58 UTC
Labels: compatibility, crash, Fixed for next patch
